<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<?pydev-testrun version="1.0"?><pydev-testsuite>
<summary errors="0" failures="1" finished="true" name="Test Run: 33" tests="1" total_time="Finished in: 0.05 secs."/>
<test location="F:\workspace\game2_httpTest\testCase\gamesdk\userlogin.py" status="fail" test="UserLogin.testUserLogin" time="">
<stdout><![CDATA[
&#35831;&#27714;&#30340;url&#26159;&#65306;http://test.rr.tv:8082/user/login

&#21709;&#24212;&#30340;body&#26159;&#65306;
{
    "data": {
        "account": "shiyuyu",
        "coins": null,
        "face": null,
        "has_discount": false,
        "has_new_giftbox": false,
        "has_new_msg": false,
        "idNo": null,
        "isRegister": false,
        "name": null,
        "needBindIdCardInfo": false,
        "need_bind": false,
        "new_user": false,
        "nickname": "shiyuyu#4819263711",
        "pay_coupon_count": null,
        "pay_coupon_count_all": null,
        "phone": "18601405271",
        "promote_coin": null,
        "register": false,
        "sid": null,
        "token": "d3a7f67ffbc549beba96374b90c8d550",
        "uid": "70065536",
        "user_point": null,
        "vip_level": null
    },
    "errorno": 200,
    "errortext": "",
    "status": true
}
]]></stdout>
<stderr><![CDATA[Traceback (most recent call last):
  File "F:\workspace\game2_httpTest\testCase\gamesdk\userlogin.py", line 69, in testUserLogin
    self.checkResult()
  File "F:\workspace\game2_httpTest\testCase\gamesdk\userlogin.py", line 82, in checkResult
    self.assertEqual(self.info['errorno'], self.errorno)
AssertionError: 200 != ''
]]></stderr>
</test>
<launch mode="run">
<launch_memento><![CDATA[<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<launchConfiguration local="true" path="game2_httpTest userlogin.py"/>
]]></launch_memento>
</launch>
</pydev-testsuite>
